version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.9
  build:
    commands:
      - echo "Building the project"
      - echo "Branch name is $BRANCH_NAME"
      - sam build --parameter-overrides "StageName=$BRANCH_NAME ApiGatewayId=$API_GATEWAY_ID"
  post_build:
    commands:
      - echo "Packaging the application"
      - sam package --s3-bucket aeb-lambda-template-bucket --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml

env:
  variables:
    API_GATEWAY_ID: "80o3umtsj3"
  exported-variables:
    - BRANCH_NAME
    - API_GATEWAY_ID
