version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.9
    commands:
      - echo "Using custom Docker image with AWS SAM CLI"
      - if [ -f "package.json" ]; then npm install; fi
      - if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

  pre_build:
    commands:
      - echo "Detecting branch"
      - chmod +x detect_branch.sh
      - . ./detect_branch.sh  # Use '.' instead of 'source' for compatibility
      - echo "Stage: $STAGE"

  build:
    commands:
      - echo "Building the SAM application"
      - sam build

  post_build:
    commands:
      - echo "Packaging the SAM application"
      - sam package --output-template-file packaged.yaml --s3-bucket aeb-lambda-template-bucket
      - echo "Deploying the SAM application"
      - sam deploy --template-file packaged.yaml --stack-name AEBLambdaTemplateStack-${STAGE} --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --parameter-overrides StageName=${STAGE}

artifacts:
  files:
    - packaged.yaml
  discard-paths: yes