version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
      python: 3.9
    commands:
      - echo "Using custom Docker image with AWS SAM CLI"
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket aeb-lambda-template-bucket
      - sam deploy --template-file packaged.yaml --stack-name AEBLambdaTemplateStack --capabilities CAPABILITY_IAM --parameter-overrides StageName=dev
artifacts:
  files:
    - packaged.yaml
