AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  StageName:
    Type: String
    Description: The stage name for the deployment (e.g., main, staging, feature-*)
  ApiGatewayId:
    Type: String
    Description: The ID of the existing API Gateway

Resources:
  Function1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ./src/function1
      AutoPublishAlias: !Ref StageName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayId
            Path: /function1
            Method: GET

  Function2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ./src/function2
      AutoPublishAlias: !Ref StageName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayId
            Path: /function2
            Method: GET

Outputs:
  Function1Arn:
    Value: !GetAtt [Function1, Arn]
    Description: "ARN of Function1"
  Function2Arn:
    Value: !GetAtt [Function2, Arn]
    Description: "ARN of Function2"
