AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  StageName:
    Type: String
    Description: The stage name for the deployment (e.g., main, staging, feature-*)
  RepoName:
    Type: String
    Description: AEB-lambda-generation

Conditions:
  IsProd: !Equals [ !Ref StageName, "main" ]

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        ADMIN_TABLE_NAME: !If 
          - IsProd
          - "admin_table_prod"
          - "admin_table_dev"

Resources:
  ApiGatewayRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${RepoName}-${StageName}"
      StageName: !Ref StageName
      Cors:
        AllowMethods: "'OPTIONS,GET,PUT,POST,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  SetAplusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: generate_aplus/index.handler
      Runtime: nodejs18.x
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess 
        - Statement:
          - Sid: LambdaInvokePolicy
            Effect: Allow
            Action: 
            - lambda:InvokeFunction
            - lambda:InvokeAsync
            Resource: '*'
      Layers:
        - arn:aws:lambda:us-east-1:466815431336:layer:axios_layer:1
        - arn:aws:lambda:us-east-1:466815431336:layer:puppeteer-core-layer:1
        - arn:aws:lambda:us-east-1:466815431336:layer:polotno-node-layer:1
      Environment:
        Variables:
          SELLER_TABLE: !If [ IsProd, seller_table_prod, seller_table_dev ]
          LISTING_GATEWAY: !If [ IsProd, 'https://9pwyqhbwx0.execute-api.us-east-1.amazonaws.com/prod', 'https://me3zf0vzl7.execute-api.us-east-1.amazonaws.com/staging' ]
          WEBSOCKET_NOTIFY_CLIENTS_ARN: !If [ IsProd, arn:aws:lambda:us-east-1:466815431336:function:AEB-lambda-listing-crud-m-FunctionWebsocketNotifyC-X2tzLX7YMxZ5, arn:aws:lambda:us-east-1:466815431336:function:AEB-lambda-listing-crud-s-FunctionWebsocketNotifyC-wgI3JldorA20 ]
          LISTING_CRUD_LAMBDA_ARN: !If [ IsProd, arn:aws:lambda:us-east-1:466815431336:function:AEB-lambda-listing-crud-m-FunctionUpdateSingleList-idDGpiIeX81h, arn:aws:lambda:us-east-1:466815431336:function:AEB-lambda-listing-crud-s-FunctionUpdateSingleList-BoF5HGVRXWco ]
          S3_BUCKET_URL: 'https://ecomtent.s3.amazonaws.com'
          S3_BUCKET_NAME: 'ecomtent'
          POLOTNO_KEY: 't0BKUibIuFTxaF3fF7Qv'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /set-aplus
            Method: post
            RestApiId: !Ref ApiGatewayRestApi

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"