AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  StageName:
    Type: String
    Description: The stage name for the deployment

Resources:
  Function1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'src/function1/index.handler'
      Runtime: 'nodejs18.x'
      FunctionName: !Sub 'Function1-${StageName}'

  Function2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'src/function2/index.handler'
      Runtime: 'nodejs18.x'
      FunctionName: !Sub 'Function2-${StageName}'

  ApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: !Ref StageName
      EndpointConfiguration: REGIONAL
      Variables: 
        STAGE_NAME: !Ref StageName

  ApiGatewayStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      StageName: !Ref StageName
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref ApiGatewayDeployment

  ApiGatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - Function1ApiGatewayAny
      - Function2ApiGatewayAny
    Properties:
      RestApiId: !Ref ApiGateway

  Function1ApiGatewayAny:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !GetAtt ApiGateway.RootResourceId
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function1.Arn}/invocations'

  Function2ApiGatewayAny:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !GetAtt ApiGateway.RootResourceId
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function2.Arn}/invocations'

Outputs:
  ApiGatewayUrl:
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
    Description: "URL for API Gateway"