AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  StageName:
    Type: String
    Description: The stage name for the deployment (e.g., main, staging, feature-*)

Resources:
  SharedApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: !Ref StageName
      EndpointConfiguration: REGIONAL

  Function1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ./src/function1
      AutoPublishAlias: !Ref StageName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref SharedApiGateway
            Path: /function1
            Method: GET

  Function2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: ./src/function2
      AutoPublishAlias: !Ref StageName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref SharedApiGateway
            Path: /function2
            Method: GET

Outputs:
  ApiGatewayUrl:
    Value: !Sub 'https://${SharedApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/'
    Description: "URL for API Gateway"
  Function1Arn:
    Value: !Ref Function1.Alias
    Description: "ARN of Function1 Alias"
  Function2Arn:
    Value: !Ref Function2.Alias
    Description: "ARN of Function2 Alias"