AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  StageName:
    Type: String
    Description: The stage name for the deployment (e.g., main, staging, feature-*)
  RepoName:
    Type: String
    Description: The name of the repository

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub "${RepoName}-${StageName}"

  FunctionHellowWorldJS:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/function_hello_world_js/
      Handler: index.handler
      Events:
        HttpApi:
          Type: Api
          Properties:
            Path: /function-hello-world-js
            Method: get
            RestApiId: !Ref ApiGateway

  FunctionQueryDBJS:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/function_query_db_js/
      Handler: index.handler
      Events:
        HttpApi:
          Type: Api
          Properties:
            Path: /function-query-db-js
            Method: get
            RestApiId: !Ref ApiGateway

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${RepoName}-${StageName}/"
  FunctionHelloWorldJSArn:
    Description: FunctionHelloWorldJS ARN
    Value: !GetAtt FunctionHelloWorldJS.Arn
  FunctionQueryDBJSArn:
    Description: FunctionQueryDBJS ARN
    Value: !GetAtt FunctionQueryDBJS.Arn