AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  StageName:
    Type: String
    Description: The stage name for the deployment (e.g., main, staging, feature-*)
  RepoName:
    Type: String
    Description: The name of the repository

Conditions:
  IsProd: !Equals [ !Ref StageName, "main" ]

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        ADMIN_TABLE_NAME: !If 
          - IsProd
          - "admin_table_prod"
          - "admin_table_dev"

Resources:
  ApiGatewayRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${RepoName}-${StageName}-api"
      StageName: !Ref StageName
      Cors:
        AllowMethods: "'OPTIONS,GET,PUT,POST,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        
  FunctionHelloWorldJS:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/function_hello_world_js/
      Handler: index.handler
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /function-hello-world-js
            Method: get
            RestApiId: !Ref ApiGatewayRestApi

  FunctionQueryDBJS:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/function_query_db_js/
      Handler: index.handler
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /function-query-db-js
            Method: get
            RestApiId: !Ref ApiGatewayRestApi

  FunctionQueryDBPython:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/function_query_db_python/
      Handler: main.handler
      Runtime: python3.9
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /function-query-db-python
            Method: get
            RestApiId: !Ref ApiGatewayRestApi

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
  FunctionHelloWorldJSArn:
    Description: FunctionHelloWorldJS ARN
    Value: !GetAtt FunctionHelloWorldJS.Arn
  FunctionQueryDBJSArn:
    Description: FunctionQueryDBJS ARN
    Value: !GetAtt FunctionQueryDBJS.Arn
  FunctionQueryDBPythonArn:
    Description: FunctionQueryDBPython ARN
    Value: !GetAtt FunctionQueryDBPython.Arn
