AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  StageName:
    Type: String
    Description: The stage name for the deployment (e.g., prod, staging)

Resources:
  SharedApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: !Ref StageName
      EndpointConfiguration: REGIONAL

  Function1:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ./lambdas/function1
      AutoPublishAlias: !Ref StageName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref SharedApiGateway
            Path: /function1
            Method: GET

  Function2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ./lambdas/function2
      AutoPublishAlias: !Ref StageName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref SharedApiGateway
            Path: /function2
            Method: GET

Outputs:
  ApiGatewayUrl:
    Value: !Sub 'https://${SharedApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/'
    Description: "URL for API Gateway"